### ISSUE TITLE
FileWrite Error

### ISSUE THREAD

**Issue by businistry** [kyaukyuai/gpt-all-star#486]
[gptallstarerror.txt](https://github.com/user-attachments/files/15938380/gptallstarerror.txt)

I get this error after a few minutes the program has been running.  I am using MacOS and M3 Hardware

**Comment by kyaukyuai** [comment]
@businistry 

Thank you for you feedback, I will check it later.

**Comment by kyaukyuai** [comment]
I checked this error, it depends on the Tools on LangChain.
Depending on the output of the LLM, it may or may not succeed.
I could not fix it right now, I will implement error handling later.
